group: travis_latest
dist: xenial
sudo: true
cache:
  directories:
    - $HOME/.cache/pip

language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"

matrix:
  allow_failures:
    - python: "3.6"
    - python: "3.7"

install:
- "curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python"
- "source $HOME/.poetry/env"
- "poetry install"

script: coverage run -m twisted.trial tests
