version: 2.1

orbs:
  python: cjw296/python-ci@2

jobs:
  run-tests:
    parameters:
      python:
        type: string
    docker:
      - image: circleci/python:<< parameters.python >>
    steps:
      - python/poetry-run-tests:
          command: "poetry run coverage run --source carly,tests -m twisted.trial tests"

  check-package:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - python/check-package:
          package: "carly"
          expect_changelog: false
          test:
          - run:
              name: "Import package"
              command: python -c "import carly"

common: &common
  jobs:

    - run-tests:
        name: python27
        python: "2.7"
    - run-tests:
        name: python36
        python: "3.6"
    - run-tests:
        name: python37
        python: "3.7"

    - python/coverage:
        name: coverage
        requires:
          - python27
          - python36
          - python37

    - python/poetry-build-package:
        name: package
        requires:
          - coverage
        filters:
          branches:
            only: master

    - check-package:
        name: check-package-python27
        image: circleci/python:2.7
        requires:
          - package

    - check-package:
        name: check-package-python37
        image: circleci/python:3.7
        requires:
          - package

    - python/release:
        name: release
        requires:
          - check-package-python27
          - check-package-python37

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 2 * * *"
          filters:
            branches:
              only: master
