version: 2.1

orbs:
  python: cjw296/python-ci@3.2

jobs:

  check-package:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - python/check-package:
          package: "carly"
          expect_changelog: false
          test:
          - run:
              name: "Import package"
              command: python -c "import carly"

common: &common
  jobs:

    - python/pip-run-tests:
        command: "coverage run --source carly,tests -m twisted.trial tests"
        matrix:
          parameters:
            image:
              - "cimg/python:3.9"
              - "cimg/python:3.10"
              - "cimg/python:3.11"

    - python/coverage:
        name: coverage
        requires:
          - python/pip-run-tests

    - python/pip-setuptools-build-package:
        name: package
        requires:
          - coverage
        filters:
          branches:
            only: master

    - check-package:
        matrix:
          parameters:
            image:
            - "cimg/python:3.7"
            - "cimg/python:3.8"
            - "cimg/python:3.9"
            - "cimg/python:3.10"
            - "cimg/python:3.11"
        requires:
          - package

    - python/release:
        name: release
        config: .carthorse.yml
        requires:
          - check-package

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 6 * * 1"
          filters:
            branches:
              only: master
