version: 2.1

orbs:
  python: cjw296/python-ci@3.2

jobs:
  run-tests:
    parameters:
      python:
        type: string
    docker:
      - image: cimg/python:<< parameters.python >>
    steps:
      - python/poetry-run-tests:
          command: "poetry run coverage run --source carly,tests -m twisted.trial tests"

  check-package:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - python/check-package:
          package: "carly"
          expect_changelog: false
          test:
          - run:
              name: "Import package"
              command: python -c "import carly"

common: &common
  jobs:

    - run-tests:
        matrix:
          parameters:
            python:
              - "3.6"
              - "3.7"
              - "3.8"
              - "3.9"
              - "3.10"
              - "3.11"

    - python/coverage:
        name: coverage
        requires:
          - run-tests

    - python/poetry-build-package:
        name: package
        requires:
          - coverage
        filters:
          branches:
            only: master

    - check-package:
        matrix:
          parameters:
            image:
            - "cimg/python:3.6"
            - "cimg/python:3.7"
            - "cimg/python:3.8"
            - "cimg/python:3.9"
            - "cimg/python:3.10"
            - "cimg/python:3.11"
        requires:
          - package

    - python/release:
        name: release
        requires:
          - check-package

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 6 * * 1"
          filters:
            branches:
              only: master
